apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  lables:
    component: web
spec:
  containers:
    - name: client
      image: jamesren11/core-client
      ports:
        - containerPort: 3000